---
- name: configure Arista EOS vlans
  arista.eos.vlans:
    state: "{{ vlan_state }}"
    config: "{{ vlan_config }}"
  register: r_eos_vlans

- name: debug vlans
  ansible.builtin.debug:
    var: r_eos_vlans
